sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - vuepress # build vuepress branch only
script:
  - yarn install
  - yarn docs:build
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GH_TOKEN
    keep-history: true
    local-dir: docs/.vuepress/dist
    target_branch: master
    on:
      all_branches: true
    local-dir: public